language: android
cache: bundler
dist: trusty
jdk: oraclejdk8
sudo: false
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - extra-google-m2repository
before_install:
  - gem install bundler
  - yes | sdkmanager "platforms;android-28"
install:
  - bundle install
script:
  - fastlane test 
