language: android
dist: trusty
jdk: oraclejdk8
sudo: false
android:
  components:
  - tools
  - platform-tools
  - build-tools-29.0.3
  - android-29
  - extra-google-m2repository
before_install:
  - gem install bundler
  - yes | sdkmanager "platforms;android-29"
install:
  - bundle install
script:
  - fastlane test 
